<a href="https://colab.research.google.com/github/rz-pb/Bioinformatics-Codes/blob/main/Levenshtein_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Levenshtein Distance
<p align = "justify">In information theory, linguistics, and computer science, the Levenshtein distance is a string metric for measuring the difference between two sequences. Informally, the Levenshtein distance between two words is the minimum number of single-character edits required to change one word into the other.</p>

In [ ]:
import numpy as np
np.set_printoptions(linewidth=200)

In [ ]:
X = "astrophysics"
Y = "prospective"

## Naive Recursion

In [ ]:
def LD_RE(A,B) :
  
  if len(A) == 0 :
    return len(B)

  if len(B) == 0 :
    return len(A)  

  if A[-1] == B[-1] :
    return LD_RE(A[0:-1] , B[0:-1])


  return 1 + min( LD_RE(A[0:-1],B[0:-1]) , LD_RE(A,B[0:-1]) , LD_RE(A[0:-1],B) )

In [ ]:
LD_RE(X,Y)

9

## Dynamic Programming


### Bottom-up


In [ ]:
LD_BU = np.full((len(Y)+1,len(X)+1), -1)

LD_BU_operations = (len(Y)+1)*(len(X)+1)*["E"]
LD_BU_operations = np.array(LD_BU_operations , dtype=str)
LD_BU_operations = np.reshape(LD_BU_operations,(len(Y)+1,len(X)+1))


def LD_DP_BU(A,B) :


  global LD_BU
  

  for i in range(0,len(B)+1) :
    for j in range(0,len(A)+1) :
      
      if i == 0 and j == 0 :
        LD_BU[i,j] = 0
        LD_BU_operations[i,j] = "N"

      if i == 0 and j != 0 :
        LD_BU[i,j] = j
        LD_BU_operations[i,j] = "D"   # DELETE
      
      if j == 0 and i != 0 :
        LD_BU[i,j] = i
        LD_BU_operations[i,j] = "I"   # INSERT


      
      if i > 0 and j > 0 :

        if A[j-1] == B[i-1] :
          LD_BU[i,j] = LD_BU[i-1,j-1]
          LD_BU_operations[i,j] = "N"  # NOTHING

        else :
          LD_BU[i,j] = min( LD_BU[i-1,j-1] + 1 , LD_BU[i,j-1] + 1 , LD_BU[i-1,j] + 1 )
          
          if LD_BU[i,j] == LD_BU[i-1,j-1] + 1 :
            LD_BU_operations[i,j] = "S" # SUBSTITUTION

          if LD_BU[i,j] == LD_BU[i,j-1] + 1 :
            LD_BU_operations[i,j] = "D" # DELETE

          if LD_BU[i,j] == LD_BU[i-1,j] + 1 :
            LD_BU_operations[i,j] = "I" # INSERT
            

  return LD_BU[-1,-1]






In [ ]:
LD_DP_BU(X,Y)

9

In [ ]:
LD_BU

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  1,  2,  3,  4,  5,  5,  6,  7,  8,  9, 10, 11],
       [ 2,  2,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  3,  3,  3,  4,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 4,  4,  3,  4,  4,  4,  4,  5,  6,  6,  7,  8,  9],
       [ 5,  5,  4,  4,  5,  5,  4,  5,  6,  7,  7,  8,  9],
       [ 6,  6,  5,  5,  5,  6,  5,  5,  6,  7,  8,  8,  9],
       [ 7,  7,  6,  6,  6,  6,  6,  6,  6,  7,  8,  8,  9],
       [ 8,  8,  7,  6,  7,  7,  7,  7,  7,  7,  8,  9,  9],
       [ 9,  9,  8,  7,  7,  8,  8,  8,  8,  8,  7,  8,  9],
       [10, 10,  9,  8,  8,  8,  9,  9,  9,  9,  8,  8,  9],
       [11, 11, 10,  9,  9,  9,  9, 10, 10, 10,  9,  9,  9]])

In [ ]:
LD_BU_operations

array([['N', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D'],
       ['I', 'S', 'D', 'D', 'D', 'D', 'N', 'D', 'D', 'D', 'D', 'D', 'D'],
       ['I', 'I', 'S', 'D', 'N', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D'],
       ['I', 'I', 'I', 'S', 'I', 'N', 'D', 'D', 'D', 'D', 'D', 'D', 'D'],
       ['I', 'I', 'N', 'I', 'S', 'I', 'S', 'D', 'D', 'N', 'D', 'D', 'N'],
       ['I', 'I', 'I', 'S', 'I', 'I', 'N', 'D', 'D', 'I', 'S', 'D', 'D'],
       ['I', 'I', 'I', 'I', 'S', 'I', 'I', 'S', 'D', 'D', 'I', 'S', 'D'],
       ['I', 'I', 'I', 'I', 'I', 'S', 'I', 'I', 'S', 'D', 'D', 'N', 'D'],
       ['I', 'I', 'I', 'N', 'I', 'I', 'I', 'I', 'I', 'S', 'D', 'I', 'S'],
       ['I', 'I', 'I', 'I', 'S', 'I', 'I', 'I', 'I', 'I', 'N', 'D', 'D'],
       ['I', 'I', 'I', 'I', 'I', 'S', 'I', 'I', 'I', 'I', 'I', 'S', 'D'],
       ['I', 'I', 'I', 'I', 'I', 'I', 'S', 'I', 'I', 'I', 'I', 'I', 'S']], dtype='<U1')

### Top-down with Memoization

In [ ]:
LD_TD = np.full((len(Y)+1,len(X)+1), -1)

LD_TD_operations = (len(Y)+1)*(len(X)+1)*["E"]
LD_TD_operations = np.array(LD_TD_operations , dtype=str)
LD_TD_operations = np.reshape(LD_TD_operations,(len(Y)+1,len(X)+1))

def LD_DP_TD(A,B) :
  
  global LD_TD

  if LD_TD[len(B),len(A)] < 0 :

    if len(A) == 0  and len(B) == 0 :
      LD_TD[len(B),len(A)] = 0
      LD_TD_operations[len(B),len(A)] = "N"


    if len(B) == 0 and len(A) != 0 :
      # LD_TD[len(B),len(A)] = len(A)
      LD_TD[len(B),len(A)] = LD_DP_TD(A[0:-1],B) + 1
      LD_TD_operations[len(B),len(A)] = "D"

    if len(A) == 0 and len(B) != 0 :
      # LD_TD[len(B),len(A)] = len(B)
      LD_TD[len(B),len(A)] = LD_DP_TD(A,B[0:-1]) + 1
      LD_TD_operations[len(B),len(A)] = "I"


    
    if len(A) > 0 and len(B) > 0 :
    
      if A[-1] == B[-1] :
        LD_TD[len(B),len(A)] = LD_DP_TD(A[0:-1] , B[0:-1])
        LD_TD_operations[len(B),len(A)] = "N"


      else :
        LD_TD[len(B),len(A)] = min( LD_DP_TD(A[0:-1],B[0:-1]) + 1 , LD_DP_TD(A,B[0:-1]) + 1 , LD_DP_TD(A[0:-1],B) + 1 )

        if LD_TD[len(B),len(A)] == (1 + LD_DP_TD(A[0:-1],B[0:-1]) ) :
          LD_TD_operations[len(B),len(A)] = "S"

        if LD_TD[len(B),len(A)] == (1 + LD_DP_TD(A[0:-1],B) ) :
          LD_TD_operations[len(B),len(A)] = "D"
        
        if LD_TD[len(B),len(A)] == (1 + LD_DP_TD(A,B[0:-1]) ) :
          LD_TD_operations[len(B),len(A)] = "I"

        




  return LD_TD[len(B),len(A)]

In [ ]:
LD_DP_TD(X,Y)

9

In [ ]:
LD_TD

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, -1],
       [ 1,  1,  2,  3,  4,  5,  5,  6,  7,  8,  9, 10, -1],
       [ 2,  2,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, -1],
       [ 3,  3,  3,  3,  4,  3,  4,  5,  6,  7,  8,  9, -1],
       [ 4,  4,  3,  4,  4,  4,  4,  5,  6,  6,  7,  8,  9],
       [ 5,  5,  4,  4,  5,  5,  4,  5,  6,  7,  7,  8,  9],
       [ 6,  6,  5,  5,  5,  6,  5,  5,  6,  7,  8,  8,  9],
       [ 7,  7,  6,  6,  6,  6,  6,  6,  6,  7,  8,  8,  9],
       [ 8,  8,  7,  6,  7,  7,  7,  7,  7,  7,  8,  9,  9],
       [ 9,  9,  8,  7,  7,  8,  8,  8,  8,  8,  7,  8,  9],
       [10, 10,  9,  8,  8,  8,  9,  9,  9,  9,  8,  8,  9],
       [11, 11, 10,  9,  9,  9,  9, 10, 10, 10,  9,  9,  9]])

In [ ]:
LD_TD == LD_BU

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True],


In [ ]:
LD_TD_operations

array([['N', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'E'],
       ['I', 'S', 'D', 'D', 'D', 'D', 'N', 'D', 'D', 'D', 'D', 'D', 'E'],
       ['I', 'I', 'S', 'D', 'N', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'E'],
       ['I', 'I', 'I', 'S', 'I', 'N', 'D', 'D', 'D', 'D', 'D', 'D', 'E'],
       ['I', 'I', 'N', 'I', 'S', 'I', 'S', 'D', 'D', 'N', 'D', 'D', 'N'],
       ['I', 'I', 'I', 'S', 'I', 'I', 'N', 'D', 'D', 'I', 'S', 'D', 'D'],
       ['I', 'I', 'I', 'I', 'S', 'I', 'I', 'S', 'D', 'D', 'I', 'S', 'D'],
       ['I', 'I', 'I', 'I', 'I', 'S', 'I', 'I', 'S', 'D', 'D', 'N', 'D'],
       ['I', 'I', 'I', 'N', 'I', 'I', 'I', 'I', 'I', 'S', 'D', 'I', 'S'],
       ['I', 'I', 'I', 'I', 'S', 'I', 'I', 'I', 'I', 'I', 'N', 'D', 'D'],
       ['I', 'I', 'I', 'I', 'I', 'S', 'I', 'I', 'I', 'I', 'I', 'S', 'D'],
       ['I', 'I', 'I', 'I', 'I', 'I', 'S', 'I', 'I', 'I', 'I', 'I', 'S']], dtype='<U1')

In [ ]:
LD_BU_operations == LD_TD_operations

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
